services:
  python:
    image: image-scraping-cvw
    container_name: cross-view-weather
    build: .
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./scraping:/app
      - ./data:/data
    ports:
      - "127.0.0.1:8080:8080"
    command: /bin/bash
    environment:
      - PYTHONUNBUFFERED=1