services:
  fastapi:
    build: .
    container_name: cross-view-weather
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
      - ./scraping:/scraping
    ports:
    - "127.0.0.1:8080:8080"
    command: /bin/bash
    environment:
      - PYTHONUNBUFFERED=1